Update codeql.yaml

diff --git a/.github/workflows/codeql.yaml b/.github/workflows/codeql.yaml
--- a/.github/workflows/codeql.yaml
+++ b/.github/workflows/codeql.yaml
@@ -5,51 +5,77 @@ on:
     branches:
       - master
 
+
 jobs:
   analyze:
-    name: Analyze
     runs-on: ubuntu-latest
-    permissions:
-      actions: read
-      contents: read
-      security-events: write
-
-    strategy:
-      fail-fast: false
-      matrix:
-        language: [ 'javascript' ] # Add your languages here
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
-    - name: Initialize CodeQL
-      uses: github/codeql-action/init@v3
-      with:
-        languages: ${{ matrix.language }}
+      - name: Initialize CodeQL
+        uses: github/codeql-action/init@v2
 
-    - name: Autobuild
-      uses: github/codeql-action/autobuild@v3
+      - name: Run CodeQL analysis
+        uses: github/codeql-action/analyze@v2
+        with:
+          # Replace with your specific queries directory or pack
+          queries: './queries'
 
-    - name: Perform CodeQL Analysis
-      uses: github/codeql-action/analyze@v3
-      with:
-        language: ${{ matrix.language }}
-        category: ${{ matrix.language }}      
+      - name: Check for Errors (using action outputs)
+        run: |
+          echo "Found ${{ steps.analyze.outputs.errorCount }} errors"
+          echo ${{ steps.analyze.outputs.errorCount }} 
+          if [[ ${{ steps.analyze.outputs.errorCount }} -gt 5 ]]; then
+            exit 1
+          fi
+        shell: bash
+
+# jobs:
+#   analyze:
+#     name: Analyze
+#     runs-on: ubuntu-latest
+#     permissions:
+#       actions: read
+#       contents: read
+#       security-events: write
+
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         language: [ 'javascript' ] # Add your languages here
+
+#     steps:
+#     - name: Checkout repository
+#       uses: actions/checkout@v3
+
+#     - name: Initialize CodeQL
+#       uses: github/codeql-action/init@v3
+#       with:
+#         languages: ${{ matrix.language }}
+
+#     - name: Autobuild
+#       uses: github/codeql-action/autobuild@v3
+
+#     - name: Perform CodeQL Analysis
+#       uses: github/codeql-action/analyze@v3
+#       with:
+#         language: ${{ matrix.language }}
+#         category: ${{ matrix.language }}      
       
-    - name: Step 3 - Use the Upload Artifact GitHub Action
-      uses: actions/upload-artifact@v2
-      with: 
-        name: assets-for-download
-        path: /home/runner/work/dependabottest/*
+#     - name: Step 3 - Use the Upload Artifact GitHub Action
+#       uses: actions/upload-artifact@v2
+#       with: 
+#         name: assets-for-download
+#         path: /home/runner/work/dependabottest/*
         
-    - name: Check for Errors (using action outputs)
-      run: |
-        # Access the number of errors directly from the action output
-        echo "Found ${{ steps.analyze.outputs.errorCount }} errors"
-        if [[ ${{ steps.analyze.outputs.errorCount }} -gt 4 ]]; then
-          exit 1
-        fi
+#     - name: Check for Errors (using action outputs)
+#       run: |
+#         # Access the number of errors directly from the action output
+#         echo "Found ${{ steps.analyze.outputs.errorCount }} errors"
+#         if [[ ${{ steps.analyze.outputs.errorCount }} -gt 4 ]]; then
+#           exit 1
+#         fi
   
     # - name: Detect Errors
     #   run: |
